export const Constants = {
    ENV_SAB_HOST: 'SAB_HOST',
    ENV_SAB_PORT: 'SAB_PORT',
    ENV_SAB_API_KEY: 'SAB_API_KEY',
    ENV_SAB_ITEM_LIMIT: 'SAB_ITEM_LIMIT',
    ENV_SAB_POLL_INTERVAL: 'SAB_POLL_INTERVAL',
    ENV_SAB_RETRY_ATTEMPTS: 'SAB_RETRY_ATTEMPTS',
    ENV_SAB_RETRY_DELAY: 'SAB_RETRY_DELAY',
    ENV_UI_THEME: 'UI_THEME',

    DEFAULT_PORT: 8080,
    DEFAULT_SSL: false,
    DEFAULT_QUEUE_LIMIT: 15,
    DEFAULT_POLL_INTERVAL: 2000,
    DEFAULT_RETRY_ATTEMPTS: 3,
    DEFAULT_RETRY_DELAY: 2000,

    DESC_HOST: 'Set host address (e.g. 192.168.1.71)',
    DESC_PORT: 'Set port number (e.g. 8080)',
    DESC_SSL: 'Uses HTTPS protocol for connection',
    DESC_API_KEY: 'Set API key (retrieved from sabnzbd',
    DESC_QUEUE_LIMIT: 'Set queue item limit',
    DESC_POLL_INTERVAL: 'Set the polling interval in milliseconds',
    DESC_RETRY_ATTEMPTS: 'Set retry attempts for API calls',
    DESC_RETRY_DELAY: 'Set delay on retry for API calls',
    DESC_THEME: 'Set UI theme',
} as const;
